name: vital_habit
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.4
  local_auth: ^2.2.0
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
