name: bloom_your_day
description: "Bloom Your Day - Habit Tracker"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.11.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  shared_preferences: ^2.5.2
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  local_auth: ^3.0.1
  screenshot: ^3.0.0
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  provider: ^6.1.2
  image_picker: ^1.0.7
  url_launcher: ^6.2.6
  in_app_review: ^2.0.9
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  google_sign_in: ^7.2.0
  confetti: ^0.8.0
  flutter_timezone: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/success.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#F4F7F9"
  color_dark: "#0F172A"
  image: "assets/icon/app_icon.png"
