// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLp_gm9bBwrgAoIss3J-NdqaktDgWd4mQ',
    appId: '1:572831008190:web:eec54fd6962c9b33a965ef',
    messagingSenderId: '572831008190',
    projectId: 'bloomyourday-dd658',
    authDomain: 'bloomyourday-dd658.firebaseapp.com',
    storageBucket: 'bloomyourday-dd658.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsdNJ9gkTyl7dlmRUbkfYvdo1dksPGxLs',
    appId: '1:572831008190:android:93a727da30da8171a965ef',
    messagingSenderId: '572831008190',
    projectId: 'bloomyourday-dd658',
    storageBucket: 'bloomyourday-dd658.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2-ipjrh1FntlXi2tdsHcU5P663mNdbP4',
    appId: '1:572831008190:ios:e1dd04ccc70c569da965ef',
    messagingSenderId: '572831008190',
    projectId: 'bloomyourday-dd658',
    storageBucket: 'bloomyourday-dd658.firebasestorage.app',
    androidClientId: '572831008190-4q3mulv08o5fu77sk9s9j4r4r4r1trkm.apps.googleusercontent.com',
    iosClientId: '572831008190-1e4m3d4ll8uon3to255a894vht7e3r0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalHabit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2-ipjrh1FntlXi2tdsHcU5P663mNdbP4',
    appId: '1:572831008190:ios:e1dd04ccc70c569da965ef',
    messagingSenderId: '572831008190',
    projectId: 'bloomyourday-dd658',
    storageBucket: 'bloomyourday-dd658.firebasestorage.app',
    androidClientId: '572831008190-4q3mulv08o5fu77sk9s9j4r4r4r1trkm.apps.googleusercontent.com',
    iosClientId: '572831008190-1e4m3d4ll8uon3to255a894vht7e3r0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalHabit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLp_gm9bBwrgAoIss3J-NdqaktDgWd4mQ',
    appId: '1:572831008190:web:288fc8e66f3ac6b1a965ef',
    messagingSenderId: '572831008190',
    projectId: 'bloomyourday-dd658',
    authDomain: 'bloomyourday-dd658.firebaseapp.com',
    storageBucket: 'bloomyourday-dd658.firebasestorage.app',
  );
}
